### ISSUE TITLE
Graph parser

### ISSUE THREAD

**Issue by bohuizhang** [VHellendoorn/ICLR20-Great#3]
Hi,

You provided a great dataset for reproducing. I was thinking that if it's possible to try other datasets for this task. I read in your paper that the graph edge types you used are borrowed a lot from Allamanis et al. (2018b), and augmented several types. So could you please provide the graph parser that you used or provide an appendix that we can follow to build such a parser?

Thanks,
Frank

**Comment by VHellendoorn** [comment]
Hi Frank,

Unfortunately, the graph parser is internal to Google; as far as I know, there are no concrete plans to make it public, nor is there officially released documentation. Having said that, building it yourself should be quite possible, as the edge types are pretty self-explanatory. You basically just need an AST parser and a data-flow analyzer; that spans all commonly used edge types.

As for public options, `srcML` with its `srcSlice` [extension](http://www.users.miamioh.edu/alomarhw/papers/JSEP14-srcSlice.pdf) can provide a language-agnostic path to making such a tool. Another example of a mature project specifically for Java is on Github [here](https://github.com/serg-Delft/j2graph). Hope that helps.

-Vincent

**Comment by egor-bogomolov** [comment]
Hi @BohuiZhang and @VHellendoorn!

I was looking for a parser that can build (G)GNN-compatible graphs for Python code recently. I also expected to find it here, but it turned out that the code of parsing cannot be open-sourced. Luckily, I found out that [Typilus](https://github.com/typilus/typilus) builds very similar graphs (even though types of edges are a bit different)!

Please, check out [a fork of Typilus](https://github.com/JetBrains-Research/typilus) that we made, which fixes some bugs in the graph generation process, tests it, and makes it a bit easier to use as a graph building tool. We already use it as a tool in another project, where we pass the data to GGNN implementation from this repo. You can find it [here](https://github.com/niksaz/semantic-code-search/blob/ggnn_encoder/src/encoders/ggnn_encoder.py) (well, the code is messy but you can get some idea on how to pass graphs extracted in jsonl.gz to the family of models from the GREAT paper).

Hope it helps, feel free to report issues!
