### ISSUE TITLE
Dead code?

### ISSUE THREAD

**Issue by mallamanis** [VHellendoorn/ICLR20-Great#4]
Hi @VHellendoorn,

It seems to me that the
* [`embed_inputs`](https://github.com/VHellendoorn/ICLR20-Great/blob/472069aba236244f8e06f9f98c565df7f9b2ea64/models/great_transformer.py#L183) for all models
* [`enc_dec_attention`](https://github.com/VHellendoorn/ICLR20-Great/blob/472069aba236244f8e06f9f98c565df7f9b2ea64/models/great_transformer.py#L161)

are never used. Are they dead code/could be deleted?

Thanks!

**Comment by VHellendoorn** [comment]
Good find! These all stem from back when each model could be called completely independently, without the `meta_model`; that use-case ended up a bit obsolete since that's not the appeal of this repository. I've removed the `embed_inputs` ones in b163efa, but I am tentatively leaving `enc_dec_attention` just in case someone who extends this toolkit to a generative setting has some use for decoder->encoder relational attention.

Thanks!

-Vincent
