### ISSUE TITLE
when i run the eval_only example ,ie. -e True, something wrong

### ISSUE THREAD

**Issue by ross-Hr** [VHellendoorn/ICLR20-Great#7]
AssertionError: Some Python objects were not bound to checkpointed values, likely due to changes in the Python program: [<tf.Variable 'attention_layer_2/q:0' shape=(512, 8, 64) dtype=float32, numpy=
...
there is my config
args = ap.parse_args(['-data_path','../dataset/great',
						  '-vocabulary_path','../vocab.txt',
						  '-config','../config.yml',
						  '-m','../models/preTModels/ggnn-checkpoint',
						  '-l','../models/preTModels/ggnn-checkpoint/ggnn-log.txt',
						  '-e','True'])

**Comment by ross-Hr** [comment]
i just use the default config.yml

**Comment by VHellendoorn** [comment]
Hi! It looks like you are importing the `ggnn` checkpoint, but since you never alter the `config.yml` file it is trying to load this into a GREAT model. Please note [line 2](https://github.com/VHellendoorn/ICLR20-Great/blob/master/config.yml#L2) of the config, where you can specify the model type. By default it is set to "great", so for you you'd want to change that to "ggnn". If you were trying to restore the GREAT model, please point it to the appropriate pretrained model directory and log file.

Hope this helps,
-Vincent

**Comment by xiaoxiong007** [comment]
> Hi! It looks like you are importing the `ggnn` checkpoint, but since you never alter the `config.yml` file it is trying to load this into a GREAT model. Please note [line 2](https://github.com/VHellendoorn/ICLR20-Great/blob/master/config.yml#L2) of the config, where you can specify the model type. By default it is set to "great", so for you you'd want to change that to "ggnn". If you were trying to restore the GREAT model, please point it to the appropriate pretrained model directory and log file.
> 
> Hope this helps,
> -Vincent

That works! 
Thank you very much for your contribution！

**Comment by ross-Hr** [comment]
> Hi! It looks like you are importing the `ggnn` checkpoint, but since you never alter the `config.yml` file it is trying to load this into a GREAT model. Please note [line 2](https://github.com/VHellendoorn/ICLR20-Great/blob/master/config.yml#L2) of the config, where you can specify the model type. By default it is set to "great", so for you you'd want to change that to "ggnn". If you were trying to restore the GREAT model, please point it to the appropriate pretrained model directory and log file.
> 
> Hope this helps,
> -Vincent

That works! 
Thank you very much for your contribution！
